### ISSUE TITLE
parallelization via docker only using 13-15% of CPU

### ISSUE THREAD

**Issue by malonzo47** [malonzo47/pynita_GUI#72]
Running demo data set with 8 cores still only uses 13-15% of CPU (both for Step 2 and Step 3).

**Comment by 0xF217** [comment]
This is not related to the source. It is related to the docker settings.
There are resource allocation settings in both Docker Desktop for Mac and Docker Desktop for Windows. These settings may require a restart of the docker.
Anyway, if you want to work with a large dataset that requires extensive resources, using docker would be not desirable because the program will only be able to consume the resource allocated from the host. 
![docker_setting_win](https://user-images.githubusercontent.com/34410700/76660537-6a793d00-6579-11ea-942d-fcaab2853404.png)
![docker_setting_mac](https://user-images.githubusercontent.com/34410700/76660544-6ea55a80-6579-11ea-8c8b-cf397c698e03.png)
